// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcmpxgymwivfkxjqvjos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbXB4Z3ltd2l2Zmt4anF2am9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDc0NjQsImV4cCI6MjA3MzkyMzQ2NH0.UsppUb91Vlux_fca-8l3yUj2vQPUAti0cO4uwIA1qvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});